import Head from "next/head";
import styles from "../../styles/Home.module.css";
import { ConnectButton } from "@rainbow-me/rainbowkit";
import dynamic from "next/dynamic";
import MintButton from "../components/MintButton";

const DynamicComponentWithNoSSR = dynamic(
  () => import("../components/Sketch"),
  { ssr: false }
);

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Zondrian</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        style={{
          display: "flex",
          justifyContent: "flex-end",
          padding: 12,
        }}
      >
        <ConnectButton />
      </div>

      <main className={styles.main}>
        <h1 className={styles.title}>Zondrian</h1>

        <p className="my-10 mx-0 text-xl text-center">
          Inspired by Piet Mondrian + Generative Art + Zora. <br />{" "}
          {"Today's mint:"}
        </p>

        <div
          className="flex justify-center items-center"
          // style={{ flex: 1, justifyContent: "center", alignItems: "center" }}
        >
          <DynamicComponentWithNoSSR />
        </div>
        <MintButton />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://twitter.com/crypblizz"
          target="_blank"
          rel="noopener noreferrer"
        >
          Twitter
        </a>
      </footer>
    </div>
  );
}
